#! /bin/bash

OBJDUMP=/opt/homebrew/opt/llvm/bin/llvm-objdump

FILE=$1
TARGET=$2

MACHINE=$(uname -s)

if [ "$MACHINE" == "Darwin" ]; then 

echo handling on Darwin
OFFSET=$($OBJDUMP  -p $FILE | grep fileoff | cut -c11-)
SIZE=$($OBJDUMP  -p $FILE | grep filesize | cut -c11-)
#set $(LANG=C objdump -h $FILE | grep .text)
#OFFSET=$(printf "%d" 0x$6)
#SIZE=$(printf "%d" 0x$3)
echo dd if=$FILE of=$TARGET bs=1 skip=$OFFSET count=$SIZE 
dd if=$FILE of=$TARGET bs=1 skip=$OFFSET count=$SIZE 

else

objcopy -j .text -O binary  $FILE $TARGET

fi
