#!/bin/sh

TARGET=$1
shift

DEBUG=$1
expr "$DEBUG" : "[-]*debug" >/dev/null 2>&1
if [ $? -eq 0 ]; then
	ENTER_DEBUG=1
	shift
fi

PARAMS=$*

LKVM=$HOME/workspace/kvmtool

set $(egrep  ^NATURE Makefile)
NATURE=$3
APP=target/aarch64-unknown-uefi/$NATURE/barekit.afx


#-kernel qemu option requires some properties from the binary file
# in some cases, the binary has no recognizable form
# the following command allows to load an arbitray binary and set start address
#qemu-system-aarch64 -nographic  -machine virt,accel=kvm -cpu host -serial mon:stdio -m 16M -device loader,file=<purebinary>,addr=0x40200000 -device loader,addr=0x40200000,cpu-num=0 

case $TARGET in

kvmtool)
	if [ "$ENTER_DEBUG" -eq "1" ]; then
		DEBUG_TAG="--debug-single-step"
	fi
	$LKVM/lkvm run --mem 16 --console serial --kernel $APP --params "$PARAMS" $DEBUG_TAG
;;

qemu-kvm)
	qemu-system-aarch64 -nographic  -machine virt,accel=kvm -cpu host -serial mon:stdio -m 16M -kernel $APP -append "$PARAMS"
;;

qemu)
	qemu-system-aarch64 -nographic  -machine virt -cpu cortex-a72 -serial mon:stdio -m 16M -kernel $APP -append "$PARAMS"
;;

qemu-uboot)
	if [ "$(uname -s)" != "Darwin" ]; then
		truncate --size 64M run_efi/QEMU_UBOOT_ENV.fd
		../u-boot/tools/env/fw_setenv -c run_efi/uboot_env.config bootargs "$PARAMS"
		ACCEL=kvm
	else
		ACCEL=hvf
	fi
	#minimum of 64M to initialize the EFI subsystem
	qemu-system-aarch64 -nographic -nodefaults -machine virt,accel=$ACCEL -cpu host -serial mon:stdio -m 64M \
		-drive if=pflash,format=raw,readonly=on,file=run_efi/QEMU_UBOOT.fd \
		-drive if=pflash,format=raw,file=run_efi/QEMU_UBOOT_ENV.fd \
		-drive file=run_efi/disk.img,format=raw,if=virtio
	;;

qemu-tfa2)
	if [ "$(uname -s)" != "Darwin" ]; then
		truncate --size 64M run_efi/QEMU_UBOOT_ENV.fd
		../u-boot/tools/env/fw_setenv -c run_efi/uboot_env.config bootargs "$PARAMS"
	fi
	truncate --size 64M run_efi/flash.bin
	dd if=../arm-trusted-firmware/build/qemu/release/bl1.bin of=run_efi/flash.bin bs=4096 conv=notrunc > /dev/null 2>&1
	dd if=../arm-trusted-firmware/build/qemu/release/fip.bin of=run_efi/flash.bin seek=64 bs=4096 conv=notrunc > /dev/null 2>&1
	#need to have 1GB of RAM in the VM for TFA to work !!!
	#https://elixir.bootlin.com/arm-trusted-firmware/v2.8/source/plat/qemu/qemu/include/platform_def.h#L181
	qemu-system-aarch64 -nographic -nodefaults -machine virt,secure=on -cpu cortex-a72 -m 1G \
		-chardev stdio,mux=on,id=char0 \
		-mon chardev=char0,mode=readline \
		-serial chardev:char0 \
		-chardev file,id=char1,path=/tmp/secuart.log \
		-serial chardev:char1 \
		-drive if=pflash,format=raw,readonly=on,file=run_efi/flash.bin \
		-drive if=pflash,format=raw,file=run_efi/QEMU_UBOOT_ENV.fd \
		-drive file=run_efi/disk.img,format=raw,if=virtio
	;;

qemu-tfa1)
	if [ "$(uname -s)" != "Darwin" ]; then
		truncate --size 64M run_efi/QEMU_UBOOT_ENV.fd
		../u-boot/tools/env/fw_setenv -c run_efi/uboot_env.config bootargs "$PARAMS"
	fi
	truncate --size 64M run_efi/flash.bin
	dd if=../arm-trusted-firmware/build/qemu/release/bl1.bin of=run_efi/flash.bin bs=4096 conv=notrunc > /dev/null 2>&1
	dd if=../arm-trusted-firmware/build/qemu/release/fip.bin of=run_efi/flash.bin seek=64 bs=4096 conv=notrunc > /dev/null 2>&1
	#need to have 1GB of RAM in the VM for TFA to work !!!
	#https://elixir.bootlin.com/arm-trusted-firmware/v2.8/source/plat/qemu/qemu/include/platform_def.h#L181
	qemu-system-aarch64 -nographic -nodefaults -machine virt,secure=on -cpu cortex-a72 -m 1G \
		-chardev stdio,mux=on,id=char0 \
		-mon chardev=char0,mode=readline \
		-serial chardev:char0 \
		-serial chardev:char0 \
		-drive if=pflash,format=raw,readonly=on,file=run_efi/flash.bin \
		-drive if=pflash,format=raw,file=run_efi/QEMU_UBOOT_ENV.fd \
		-drive file=run_efi/disk.img,format=raw,if=virtio
	;;

qemu-el3)
	#need to have 1GB of RAM in the VM for TFA to work !!!
	#https://elixir.bootlin.com/arm-trusted-firmware/v2.8/source/plat/qemu/qemu/include/platform_def.h#L181
	qemu-system-aarch64 -nographic -nodefaults -machine virt,secure=on -cpu cortex-a72 -m 1G \
		-chardev stdio,mux=on,id=char0 \
		-mon chardev=char0,mode=readline \
		-serial chardev:char0 \
		-serial chardev:char0 \
		-device loader,file=$APP,addr=0x40200000 -device loader,addr=0x40200000,cpu-num=0 
	;;

esac

